version: 2
build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
sphinx:
  configuration: source/conf.py
  builder: "dirhtml"
formats:
  - pdf
  - epub
python:
  install:
    - requirements: requirements.txt
submodules:
  include: all
  recursive: true
